INSERT INTO quiz (content,choice1,choice2,choice3,choice4,answer) VALUES ('フリップフロップ回路を利用した高速なメモリはどれか？','DRAM','RDRAM','SDRAM','SRAM',4);
INSERT INTO quiz (content,choice1,choice2,choice3,choice4,answer) VALUES ('50MIPSのプロセッサの平均命令実行時間は幾らか？','20ナノ秒','50ナノ秒','2マイクロ秒','5マイクロ秒',1);
INSERT INTO quiz (content,choice1,choice2,choice3,choice4,answer) VALUES ('UMLの図のうち、業務要件定義において、業務フローを記述する際に使用する、処理の分岐や並行処理、処理の同期などを表現できる図はどれか？','アクティビティ図','クラス図','状態遷移図','ユースケース図',1);
INSERT INTO quiz (content,choice1,choice2,choice3,choice4,answer) VALUES ('トランザクションが，データベースに対する更新処理を完全に行うか，全く処理しなかったのように取り消すか，のどちらかの結果になることを保証する特性はどれか？','一貫性(consistency)','原子性(atomicity)','耐久性(durability)','独立性(isolation)',2);
INSERT INTO quiz (content,choice1,choice2,choice3,choice4,answer) VALUES ('アジャイル開発手法のスクラムにおいて，開発チームの全員が1人ずつ"昨日やったこと"，"今日やること"，"障害になっていること"などを話し，全員でプロジェクトの状況を共有するイベントはどれか？','スプリントプランニング','スプリントレビュー','デイリースクラム','レトロスペクティブ',3);
INSERT INTO quiz (content,choice1,choice2,choice3,choice4,answer) VALUES ('IPv4ネットワークにおいて，ネットワークの疎通確認に使われるものはどれか？','BOOTP','DHCP','MIB','ping',4);
INSERT INTO quiz (content,choice1,choice2,choice3,choice4,answer) VALUES ('固定区画方式を使用した主記憶において，大きさが100kバイト，200kバイト，300kバイト，400kバイトの区画をそれぞれ一つ設定する。この主記憶に，大きさが250kバイト，250kバイト，50kバイトのプログラムをベストフィット方式で割り当てた。この時点で，使用できない領域は合計で何kバイト生じているか。',200,250,350,450,2);
INSERT INTO quiz (content,choice1,choice2,choice3,choice4,answer) VALUES ('Webアプリケーションの脆弱性対策のためのWAFの設置場所として最も適切な箇所はどこか。ここで，WAFには通信を暗号化したり復号したりする機能はないものとする。','ファイヤウォール','SSLアクセラレータ','Webサーバ','データベースサーバ',3);
INSERT INTO quiz (content,choice1,choice2,choice3,choice4,answer) VALUES ('割込み処理の終了後に割込みによって中断された処理を割り込まれた場所から再開するために，割込み発生時にプロセッサが保存するものはどれか。','インデックスレジスタ','データレジスタ','プログラムカウンタ','命令レジスタ',3);
INSERT INTO quiz (content,choice1,choice2,choice3,choice4,answer) VALUES ('AES-256で暗号化されていることが分かっている暗号文が与えられているとき，ブルートフォース攻撃で鍵と解読した平文を得るまでに必要な試行回数の最大値はどれか。','256','2の128乗','2の255乗','2の256乗',4);
INSERT INTO quiz (content,choice1,choice2,choice3,choice4,answer) VALUES ('モジュール間の情報の受渡しがパラメタだけで行われる，結合度が最も弱いモジュール結合はどれか。','共通結合','制御結合','データ結合','内容結合',3);
INSERT INTO quiz (content,choice1,choice2,choice3,choice4,answer) VALUES('OSが記憶領域の割当てと解放を繰り返すことによって，細切れの未使用領域が多数できてしまう場合がある。この現象を何というか。','コンパクション','スワッピング','フラグメンテーション','ページング',3);
INSERT INTO quiz (content,choice1,choice2,choice3,choice4,answer) VALUES('プログラムを構成するモジュールの結合を，プログラムの実行時に行う方式はどれか。','インタプリタ','オーバーレイ','静的リンキング','動的リンキング',4);
INSERT INTO quiz (content,choice1,choice2,choice3,choice4,answer) VALUES('ソフトウェアの統合開発環境として提供されているOSSはどれか。','Eclipse','GCC','Linux','Tomcat',1);
INSERT INTO quiz (content,choice1,choice2,choice3,choice4,answer) VALUES('OSI基本参照モデルにおいて，エンドシステム間のデータ伝送の中継と経路制御の機能をもつ層はどれか。','セション層','データリンク層','トランスポート層','ネットワーク層',4);
INSERT INTO quiz (content,choice1,choice2,choice3,choice4,answer) VALUES('SWOT分析を用いて識別した，自社製品に関する外部要因はどれか。','機能面における強み','コスト競争力','新規参入による脅威','品質における弱み',3);
INSERT INTO quiz (content,choice1,choice2,choice3,choice4,answer) VALUES('コンデンサに蓄えた電荷の有無で情報を記憶するメモリはどれか。','EEPROM','SDRAM','SRAM','フラッシュメモリ',2);
INSERT INTO quiz (content,choice1,choice2,choice3,choice4,answer) VALUES('SQL文においてFOREIGN KEYとREFERENCESを用いて指定する制約はどれか。','キー制約','検査制約','参照制約','表明',3);
INSERT INTO quiz (content,choice1,choice2,choice3,choice4,answer) VALUES('トランザクション処理プログラムが，データベース更新の途中で異常終了した場合，ロールバック処理によってデータベースを復元する。このとき使用する情報はどれか。','最新のスナップショット情報','最新のバックアップファイル情報','ログファイルの更新後情報','ログファイルの更新前情報',4);
INSERT INTO quiz (content,choice1,choice2,choice3,choice4,answer) VALUES('トランスポート層のプロトコルであり，信頼性よりもリアルタイム性が重視される場合に用いられるものはどれか。','HTTP','IP','TCP','UDP',4);
INSERT INTO quiz (content,choice1,choice2,choice3,choice4,answer) VALUES('UML2.0において，オブジェクト間の相互作用を時系列に表す図はどれか。','アクティビティ図','コンポーネント図','シーケンス図','状態遷移図',3);
INSERT INTO quiz (content,choice1,choice2,choice3,choice4,answer) VALUES('コンピュータやネットワークのセキュリティ上の脆弱性を発見するために，システムを実際に攻撃して侵入を試みる手法はどれか。','ウォークスルー','ソフトウェアインスペクション','ペネトレーションテスト','リグレッションテスト',3);
INSERT INTO quiz (content,choice1,choice2,choice3,choice4,answer) VALUES('音声などのアナログデータをデジタル化するために用いられるPCMにおいて，音の信号を一定の周期でアナログ値のまま切り出す処理はどれか。','暗号化','標本化','符号化','量子化',2);
INSERT INTO quiz (content,choice1,choice2,choice3,choice4,answer) VALUES('OSI基本参照モデルのトランスポート層以上が異なるLANシステム相互間でプロトコル変換を行う機器はどれか。','ゲートウェイ','ブリッジ','リピータ','ルータ',1);
INSERT INTO quiz (content,choice1,choice2,choice3,choice4,answer) VALUES('ルータがパケットの経路決定に用いる情報として，最も適切なものはどれか。','宛先IPアドレス','宛先MACアドレス','発信元IPアドレス','発信元MACアドレス',1);
INSERT INTO quiz (content,choice1,choice2,choice3,choice4,answer) VALUES('IPv4アドレス 128.0.0.0 を含むアドレスクラスはどれか。','クラスA','クラスB','クラスC','クラスD',2);
INSERT INTO quiz (content,choice1,choice2,choice3,choice4,answer) VALUES('公開鍵暗号方式の暗号アルゴリズムはどれか。','AES','KCipher-2','RSA','SHA-256',3);
INSERT INTO quiz (content,choice1,choice2,choice3,choice4,answer) VALUES('システムの外部設計を完了させるとき，顧客から承認を受けるものはどれか。','画面レイアウト','システム開発計画','物理データベース仕様','プログラム流れ図',1);
INSERT INTO quiz (content,choice1,choice2,choice3,choice4,answer) VALUES('割込み処理の終了後に割込みによって中断された処理を割り込まれた場所から再開するために，割込み発生時にプロセッサが保存するものはどれか。','インデックスレジスタ','データレジスタ','プログラムカウンター','命令レジスタ',3);
INSERT INTO quiz (content,choice1,choice2,choice3,choice4,answer) VALUES('手続型言語のコンパイラが行う処理のうち，最初に行う処理はどれか。','意味解析','構文解析','最適化','字句解析',4);
